name: learn
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1


environment:
  sdk: '>=3.2.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^1.2.0
  intl: ^0.19.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  # Icons Images
  - ./assets/images/appIcons/icon-steak.png
  - ./assets/images/appIcons/check-circle.png
  - ./assets/images/mascote/icon-loja-default.png
  - ./assets/images/mascote/icon-atividades-default.png
  - ./assets/images/mascote/icon-roupas-default.png
  - ./assets/images/mascote/icon-alimentos-default.png
  - ./assets/images/appIcons/icon-atividades-default.png
  - ./assets/images/appIcons/icon-atividades-select.png
  - ./assets/images/appIcons/icon-home-default.png
  - ./assets/images/appIcons/icon-home-select.png
  - ./assets/images/appIcons/icon-mascote-default.png
  - ./assets/images/appIcons/icon-mascote-select.png
  - ./assets/images/appIcons/icon-monitorar-default.png
  - ./assets/images/appIcons/icon-monitorar-select.png
  - ./assets/images/appIcons/icon-perfil-default.png
  - ./assets/images/appIcons/icon-perfil-select.png
  - ./assets/images/appIcons/progressFieldWithStars.png
  - ./assets/images/appIcons/progressFieldWithStarsBlue.png
  - ./assets/images/appIcons/icon-trophie.png
  - ./assets/images/appIcons/icon-award.png
  - ./assets/images/appIcons/icon-lock-default.png
  # Badges
  - ./assets/images/appIcons/badge-bronze-default.png
  - ./assets/images/appIcons/badge-bronze-blue.png
  - ./assets/images/appIcons/badge-prata-default.png
  - ./assets/images/appIcons/badge-prata-blue.png
  - ./assets/images/appIcons/badge-ouro-default.png
  - ./assets/images/appIcons/badge-ouro-blue.png
  - ./assets/images/appIcons/badge-diamante-default.png
  - ./assets/images/appIcons/badge-diamante-blue.png
  - ./assets/images/appIcons/silver-badge.png
  # Person Images
  - ./assets/images/appImages/ianzinho.jpg
  # Mascot Images
  - ./assets/images/mascote/background.png
  - ./assets/images/mascote/backgroundLarge.png
  - ./assets/images/mascote/mascot-happy.png
  - ./assets/images/mascote/mascot-sad.png
  - ./assets/images/mascote/mascote.png

  # App Images
  - ./assets/images/appImages/icon.png


  fonts:
  - family: Fieldwork-Geo
    fonts:
     - asset: assets/fonts/Fieldwork/Fieldwork10GeoRegular.otf
       weight: 400
     - asset: assets/fonts/Fieldwork/Fieldwork13SemiBoldGeo.otf
       weight: 600
     - asset: assets/fonts/Fieldwork/Fieldwork16GeoBold.otf
       weight: 700
     - asset: assets/fonts/Fieldwork/Fieldwork19GeoBlack.otf
       weight: 900
     - asset: assets/fonts/Fieldwork/Fieldwork1GeoHair.otf
       weight: 100
     - asset: assets/fonts/Fieldwork/Fieldwork22GeoFat.otf
       weight: 800
     - asset: assets/fonts/Fieldwork/Fieldwork4GeoThin.otf
       weight: 200
     - asset: assets/fonts/Fieldwork/Fieldwork7GeoLight.otf
       weight: 300
  
  - family: Fieldwork-Hum
    fonts:
      - asset: assets/fonts/Fieldwork/Fieldwork11HumRegular.otf
        weight: 400
      - asset: assets/fonts/Fieldwork/Fieldwork14HumDemiBold.otf
        weight: 600
      - asset: assets/fonts/Fieldwork/Fieldwork17HumBold.otf
        weight: 700
      - asset: assets/fonts/Fieldwork/Fieldwork20HumBlack.otf
        weight: 900
      - asset: assets/fonts/Fieldwork/Fieldwork23HumFat.otf
        weight: 800
      - asset: assets/fonts/Fieldwork/Fieldwork2HumHair.otf
        weight: 100
      - asset: assets/fonts/Fieldwork/Fieldwork5HumThin.otf
        weight: 200
      - asset: assets/fonts/Fieldwork/Fieldwork8HumLight.otf
        weight: 300

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
